### ISSUE TITLE
How can we use logical operators ? Need urgent help

### ISSUE THREAD

**Issue by Mujtaba1986** [Happy-Algorithms-League/hal-cgp#382] opened 2023-09-20 16:29 UTC
Hey,

I am trying to solve 3-bit parity problem. The perfect solution should have two XOR gates. Each gate will have two inputs, the overall program will work on 3 inputs and 1 output. 

Now the problem is that the cgp library doesn't work with logical operators. Any idea how to solve this issue? 

I have tried implementing XOR with an equivalent maths expression, it works but doesn't print the expression. Actually the programs stucks at this line 

print(f"evolved function: {pop.champion.to_sympy()}")

Here is the function i want to implement: 

class XOR(cgp.OperatorNode):
    """ A node that XOR its input.
    """
    _arity = 2
   
    #_def_output = "x_0 ^ x_1"    option 1
    #_def_output = "x_0 or x_1"    option 2

   
    #_def_output = "np.bitwise_and(x_0,x_1) " trued this but doesn't work
    
    _def_output = "x_0+x_1 -x_0*x_1*(1 +x_0+x_1-x_0*x_1)"  # it finds solution but then can't print

**Comment by Mujtaba1986** [comment] 2023-09-20 16:31
Seems like the community is not very active

**Comment by jakobj** [comment] 2024-02-12 23:58
hi @Mujtaba1986, i'm not entirely sure what the problem is, but implementing logical nodes indeed requires a few small internal changes. i have a working version with an example for the three bit parity generator, will create a PR tomorrow.

**Comment by jakobj** [comment] 2024-02-13 01:32
here's one implementation https://github.com/Happy-Algorithms-League/hal-cgp/pull/386

hope it's useful and works for you, let me know

**Comment by jakobj** [comment] 2024-02-14 19:19
with #386 merged, this is solved

**Closed by jakobj** 2024-02-14 19:19 UTC
Labels: enhancement
