### ISSUE TITLE
Evolve stops after second iteration

### ISSUE THREAD

**Issue by galleon** [Happy-Algorithms-League/hal-cgp#288] opened 2021-02-02 20:33 UTC
Hello, any clue why the `evolve` function stops after 2 iterations only with some parameters ?

A piece of code reproducing the error can be found [here](https://gist.github.com/galleon/c6e3e1111ecdc5b0d52a9825da3c8322). The code has no meaning and is derived from my application.

**Comment by mschmidt87** [comment] 2021-02-03 00:29
When I execute your code, the evolution stops after 2 iterations with fitness value 3.049. Your min_fitness is set to 2 so that is why the evolution stops. 
Now, there is some weird behavior making the programm just hang instead of properly closing, which happens when you use parallel processes (`n_processes : 4`). If you use 1 process, the programm finishes.

So, in a nutshell: It is expected behavior that the evolution stops because you've exceeded the min_fitness. However, for the parallel processes, the programm does not finish properly, so we should look into this, @jakobj .

**Comment by galleon** [comment] 2021-02-03 06:28
Thanks @mschmidt87 for the quick answer. The parameters were probably not fully understood on my side. I leave it to you to close the issue or rename it.

**Comment by jakobj** [comment] 2021-02-04 12:21
hmm, i'm having trouble reproducing your issue. both with a single as well as multiple processes, the program finishes as intended. i tested with hal-cgp 0.2.0. python 3.7.2. @mschmidt87 can you describe under which conditions it hangs?

**Comment by mschmidt87** [comment] 2021-02-05 12:28
Yes, sorry, I checked with the release version and the current master and it indeed finishes correctly for me, too. Therefore closing this issue.

**Closed by mschmidt87** 2021-02-05 12:28 UTC
